CREATE TABLE Transacciones (
    ID_TRANSACCION VARCHAR(50) PRIMARY KEY,
    ID_ORIGEN VARCHAR(50) REFERENCES Cuenta(ID_CUENTA),
    ID_DESTINO VARCHAR(50) REFERENCES Cuenta(ID_CUENTA),
    MONTO DECIMAL(12, 2),
    FECHA_HORA TIMESTAMP,
    ESTADO VARCHAR(20)
);
